### ISSUE TITLE
AMD OpenCL ports of the libs

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana-perf-libs#52]
OpenCL ports of the cuda code.

**Comment by glupescu** [comment]
I've started looking into this. I've forked the repo and working on an OpenCL port from CUDA.

Doing the development and testing on a cluster system with K40M.

**Comment by awrelll** [comment]
Go @glupescu !!! :D

**Comment by sakridge** [comment]
@glupescu you might look into converting to HIP from cuda:

https://github.com/ROCm-Developer-Tools/HIP

Although you would need an AMD platform to run it on.

**Comment by glupescu** [comment]
> @glupescu you might look into converting to HIP from cuda:
> 
> https://github.com/ROCm-Developer-Tools/HIP
> 
> Although you would need an AMD platform to run it on.

I'll do a manual port since it's the best way, given I didn't see any complicated features from CUDA used. Also didn't work with ROCm because had tons of problems with ROCm on Linux.

I have at home a hybrid AMD-NVIDIA platform, and OpenCL works fine on both, but this is on Windows. To make solano perf lib work on Windows via cygwin/cl.exe would take some time.

On Linux, the APU I have from AMD has no proper support from AMD (Ryzen 2400G) and OpenCL is not usable, hence I don't have an AMD OpenCL Linux platform to develop on.

I'll hence do the port on a cluster with K40M and Linux, which supports both CUDA and OpenCL, and then I'll see if there is room for a more broader support/test.
